name: new landingzone
description: create a new landingzone
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to create a new landingzone.

  - type: input
    id: labName
    attributes:
      label: lab Name
      description: 
      placeholder: cool-azure-project
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: environment
      multiple: false
      description:
      options: 
        - test
        - prod
      default: 0
    validations:
      required: true

  - type: dropdown
    id: billingScope
    attributes:
      label: billingScope
      multiple: false
      description:
      options: 
        - platform
      default: 0
    validations:
      required: false

  - type: dropdown
    id: managementGroupName
    attributes:
      label: management group name
      multiple: false
      description:
      options: 
        - online
        - playground
        - platform
      default: 0
    validations:
      required: true

  - type: dropdown
    id: managementGroupHierarchy
    attributes:
      label: management group hierarchy
      multiple: false
      description:
      options: 
        - prod
        - test
      default: 0
    validations:
      required: true

  - type: input
    id: budget
    attributes:
      label: budget
      description: 
      placeholder: "100"
    validations:
      required: true

  - type: input
    id: subscriptionId
    attributes:
      label: convert empty subscription tot a landingzone
      description: 
      placeholder: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    validations:
      required: false

  - type: input
    id: githubRepoName
    attributes:
      label: GitHub repo name
      description:
      placeholder: landingzone
    validations:
      required: true

  - type: input
    id: ownerEmail
    attributes:
      label: owner email
      description: pam param
      placeholder: foo@gazelle.cloud
    validations:
      required: true

  - type: input
    id: engineer
    attributes:
      label: tag engineer
      description: pam param
      placeholder: bar@gazelle.cloud
    validations:
      required: true
